version: "3"
services:
    webapp-server:
        build:
            context: .
            dockerfile: Dockerfile-PHP
        volumes:
            - "./:/var/www/html/"
            - "./files/000-default.conf:/etc/apache2/sites-available/000-default.conf"
        ports:
            - "127.0.0.1:8282:80"
    mysql-server:
        image: "mysql:8.0.30"
        environment:
            MYSQL_ROOT_PASSWORD: "*AF36CD090DFB1109F6DA00D0AA4106B3AF1970E3"
            MYSQL_DATABASE: topchemicalpest
        volumes:
            - mysql-data:/var/lib/mysql/
        ports:
            - "127.0.0.1:3306:3306"
        restart: always

    redis-server:
        image: "redis:7.0.4"

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "127.0.0.1:8080:80"
        environment:
            - PMA_ARBITRARY=1

volumes:
  mysql-data:
